package nl.fontys.sebivenlo.dao;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Identifies the ID field of an Entity.
 * 
 * Just adding the annotation will tag the id generated, i.e. typically using some sequence.
 * Use @ID(generated=false) if you have a natural key that should NOT be generated.
 * 
 * @author Pieter van den Hombergh  {@code p.vandenhombergh@fontys.nl}
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface ID {
    /**
     * Is the ID generated by the persistence layer.
     * @return true by default, not if set as parameter
     */
    boolean generated() default true;
}
